const USER_AUTH_REGISTER =  {
    REQUEST: "USER_AUTH_REGISTER_REQUEST",
    SUCCESS: "USER_AUTH_REGISTER_SUCCESS",
    ERROR: "USER_AUTH_REGISTER_ERROR"
}

const USER_AUTH_LOGIN = 'USER_AUTH_LOGIN'
const USER_AUTH_LOG_OUT = 'USER_AUTH_LOG_OUT'

const GET_TOURS_LIST = 'GET_TOURS_LIST'

export {
    USER_AUTH_REGISTER,
    USER_AUTH_LOGIN,
    USER_AUTH_LOG_OUT,


    GET_TOURS_LIST,
}